[build]
  # Lệnh build: Biên dịch code xong thì copy folder images vào thư mục dist
  command = "npm run build && cp -r images dist/"
  
  # Thư mục mà Netlify sẽ dùng để chạy web
  publish = "dist"

[[redirects]]
  # Chống lỗi 404 khi người dùng nhấn F5 (Refresh) trang web
  from = "/*"
  to = "/index.html"
  status = 200